2018-04-20 03:10:56,021 ERROR 38680 nodejs.ClusterClientNoResponseError: client no response in 10815291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 38680
hostname: loveRain.local

2018-04-20 09:57:57,038 ERROR 38680 nodejs.ClusterClientNoResponseError: client no response in 24400246ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 38680
hostname: loveRain.local

2018-04-20 12:10:22,299 ERROR 44658 [-/192.168.10.158/-/32ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44658
hostname: loveRain.local

2018-04-20 12:10:58,333 ERROR 44658 [-/192.168.10.158/-/25ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44658
hostname: loveRain.local

2018-04-20 12:11:13,912 ERROR 44658 [-/192.168.10.158/-/29ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44658
hostname: loveRain.local

2018-04-20 12:11:51,771 ERROR 44658 [-/192.168.10.158/-/11ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44658
hostname: loveRain.local

2018-04-20 12:11:57,501 ERROR 44658 [-/192.168.10.158/-/5ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44658
hostname: loveRain.local

2018-04-20 12:14:49,641 ERROR 44960 [-/192.168.10.158/-/76ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44960
hostname: loveRain.local

2018-04-20 12:14:53,000 ERROR 44960 [-/192.168.10.158/-/12ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `name` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `name` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `name` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 44960
hostname: loveRain.local

2018-04-20 12:16:03,336 ERROR 45022 [-/192.168.10.158/-/69ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `id` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 45022
hostname: loveRain.local

2018-04-20 12:16:07,988 ERROR 45022 [-/192.168.10.158/-/11ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = 2 AND `key` = '1'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = '1'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `id` = 2 AND `key` = \'1\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = \'1\''
name: 'ER_PARSE_ERRORError'
pid: 45022
hostname: loveRain.local

2018-04-20 12:17:22,328 ERROR 45022 [-/192.168.10.158/-/9ms POST /api] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = 2 AND `key` = '123456'' at line 1
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = '123456'
code: 'ER_PARSE_ERROR'
errno: 1064
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'WHERE `id` = 2 AND `key` = \'123456\'\' at line 1'
sqlState: '42000'
index: 0
sql: 'UPDATE `cd_user` SET  WHERE `id` = 2 AND `key` = \'123456\''
name: 'ER_PARSE_ERRORError'
pid: 45022
hostname: loveRain.local

2018-04-20 13:27:52,339 ERROR 47694 [-/127.0.0.1/-/17ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47694
hostname: loveRain.local

2018-04-20 13:27:53,216 ERROR 47694 [-/127.0.0.1/-/2ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47694
hostname: loveRain.local

2018-04-20 13:27:58,267 ERROR 47694 [-/127.0.0.1/-/0ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47694
hostname: loveRain.local

2018-04-20 13:28:13,287 ERROR 47774 [-/127.0.0.1/-/12ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47774
hostname: loveRain.local

2018-04-20 13:28:14,337 ERROR 47774 [-/127.0.0.1/-/2ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47774
hostname: loveRain.local

2018-04-20 13:28:14,955 ERROR 47774 [-/127.0.0.1/-/1ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47774
hostname: loveRain.local

2018-04-20 13:31:04,246 ERROR 47774 [-/127.0.0.1/-/7ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47774
hostname: loveRain.local

2018-04-20 13:31:22,311 ERROR 47977 [-/127.0.0.1/-/21ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:23,015 ERROR 47977 [-/127.0.0.1/-/2ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:23,591 ERROR 47977 [-/127.0.0.1/-/1ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:23,903 ERROR 47977 [-/127.0.0.1/-/2ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:24,101 ERROR 47977 [-/127.0.0.1/-/1ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:24,261 ERROR 47977 [-/127.0.0.1/-/2ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:24,419 ERROR 47977 [-/127.0.0.1/-/1ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:31:50,650 ERROR 47977 [-/127.0.0.1/-/1ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:18:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47977
hostname: loveRain.local

2018-04-20 13:35:18,560 ERROR 48138 [-/127.0.0.1/-/31ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:19:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 48138
hostname: loveRain.local

2018-04-20 13:35:48,834 ERROR 48138 [-/127.0.0.1/-/5ms GET /download] nodejs.ReferenceError: fs is not defined
    at HomeController.download (/Users/chz/Desktop/credit/app/controller/home.js:19:21)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 48138
hostname: loveRain.local

